package ru.danilakondr.netalbum.api;

public enum RequestType {
	  INIT_SESSION
	, RESTORE_SESSION
	, CONNECT_TO_SESSION
	, DISCONNECT_FROM_SESSION
	, CLOSE_SESSION
	, GET_DIRECTORY_INFO
	, ADD_IMAGES
	, DOWNLOAD_THUMBNAILS
	, SYNCHRONIZE
	;
}
