/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ru.danilakondr.netalbum.client.gui;

import java.awt.Point;
import java.io.File;
import java.io.IOException;
import java.net.URI;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.YES_NO_OPTION;
import javax.swing.SwingUtilities;
import ru.danilakondr.netalbum.api.data.Change;
import static ru.danilakondr.netalbum.api.data.Change.Type.ADD_FOLDER;
import static ru.danilakondr.netalbum.api.data.Change.Type.RENAME_DIR;
import static ru.danilakondr.netalbum.api.data.Change.Type.RENAME_FILE;
import ru.danilakondr.netalbum.client.connect.SessionTable;
import ru.danilakondr.netalbum.client.connect.Session;
import ru.danilakondr.netalbum.api.message.Response;
import static ru.danilakondr.netalbum.api.message.Response.Error.Status.CLIENT_ALREADY_CONNECTED;
import static ru.danilakondr.netalbum.api.message.Response.Error.Status.CLIENT_NOT_CONNECTED;
import static ru.danilakondr.netalbum.api.message.Response.Error.Status.EXCEPTION;
import static ru.danilakondr.netalbum.api.message.Response.Error.Status.FILE_ALREADY_EXISTS;
import static ru.danilakondr.netalbum.api.message.Response.Error.Status.FILE_NOT_FOUND;
import static ru.danilakondr.netalbum.api.message.Response.Error.Status.INVALID_REQUEST;
import static ru.danilakondr.netalbum.api.message.Response.Error.Status.NON_EXISTENT_SESSION;
import static ru.danilakondr.netalbum.api.message.Response.Error.Status.NOT_AN_INITIATOR;
import static ru.danilakondr.netalbum.api.message.Response.Error.Status.NOT_A_VIEWER;
import ru.danilakondr.netalbum.client.NetAlbumPreferences;
import ru.danilakondr.netalbum.client.SessionInfo;

/**
 *
 * @author danko
 */
public class SessionControlForm extends javax.swing.JFrame {
    private final SessionTable sessionTable = new SessionTable();
    private NetAlbumPreferences cfg;
    
    /**
     * Creates new form SessionControlForm
     */
    public SessionControlForm() {
        initComponents();
    }
    
    public void setConfiguration(NetAlbumPreferences cfg) {
        this.cfg = cfg;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contextMenu = new javax.swing.JPopupMenu();
        miViewSession = new javax.swing.JMenuItem();
        miCloseSessions = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSessionList = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        miInitSession = new javax.swing.JMenuItem();
        miOpenSession = new javax.swing.JMenuItem();
        javax.swing.JPopupMenu.Separator jSeparator1 = new javax.swing.JPopupMenu.Separator();
        miPreferences = new javax.swing.JMenuItem();
        javax.swing.JPopupMenu.Separator jSeparator2 = new javax.swing.JPopupMenu.Separator();
        miCloseAllSessions = new javax.swing.JMenuItem();
        miExit = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        miAbout = new javax.swing.JMenuItem();

        miViewSession.setText(java.text.MessageFormat.format(java.util.ResourceBundle.getBundle("ru/danilakondr/netalbum/client/gui/Strings").getString("contextMenu.ViewSessionProperties"), new Object[] {})); // NOI18N
        miViewSession.setToolTipText("");
        miViewSession.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miViewSessionActionPerformed(evt);
            }
        });
        contextMenu.add(miViewSession);

        miCloseSessions.setText(java.text.MessageFormat.format(java.util.ResourceBundle.getBundle("ru/danilakondr/netalbum/client/gui/Strings").getString("contextMenu.CloseSelectedSessions"), new Object[] {})); // NOI18N
        miCloseSessions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCloseSessionsActionPerformed(evt);
            }
        });
        contextMenu.add(miCloseSessions);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblSessionList.setModel(sessionTable);
        tblSessionList.setComponentPopupMenu(contextMenu);
        tblSessionList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblSessionListMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblSessionList);

        fileMenu.setText(java.text.MessageFormat.format(java.util.ResourceBundle.getBundle("ru/danilakondr/netalbum/client/gui/Strings").getString("menu.File"), new Object[] {})); // NOI18N

        miInitSession.setText(java.text.MessageFormat.format(java.util.ResourceBundle.getBundle("ru/danilakondr/netalbum/client/gui/Strings").getString("menu.File.NewFolder"), new Object[] {})); // NOI18N
        miInitSession.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miInitSessionActionPerformed(evt);
            }
        });
        fileMenu.add(miInitSession);

        miOpenSession.setText(java.text.MessageFormat.format(java.util.ResourceBundle.getBundle("ru/danilakondr/netalbum/client/gui/Strings").getString("menu.File.OpenFolder"), new Object[] {})); // NOI18N
        fileMenu.add(miOpenSession);
        fileMenu.add(jSeparator1);

        miPreferences.setText(java.text.MessageFormat.format(java.util.ResourceBundle.getBundle("ru/danilakondr/netalbum/client/gui/Strings").getString("menu.File.Configuration"), new Object[] {})); // NOI18N
        miPreferences.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPreferencesActionPerformed(evt);
            }
        });
        fileMenu.add(miPreferences);
        fileMenu.add(jSeparator2);

        miCloseAllSessions.setText(java.text.MessageFormat.format(java.util.ResourceBundle.getBundle("ru/danilakondr/netalbum/client/gui/Strings").getString("menu.File.CloseAllSessions"), new Object[] {})); // NOI18N
        miCloseAllSessions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCloseAllSessionsActionPerformed(evt);
            }
        });
        fileMenu.add(miCloseAllSessions);

        miExit.setText(java.text.MessageFormat.format(java.util.ResourceBundle.getBundle("ru/danilakondr/netalbum/client/gui/Strings").getString("menu.File.Quit"), new Object[] {})); // NOI18N
        miExit.setToolTipText("");
        miExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miExitActionPerformed(evt);
            }
        });
        fileMenu.add(miExit);

        jMenuBar1.add(fileMenu);

        helpMenu.setText(java.text.MessageFormat.format(java.util.ResourceBundle.getBundle("ru/danilakondr/netalbum/client/gui/Strings").getString("menu.Help"), new Object[] {})); // NOI18N

        miAbout.setText(java.text.MessageFormat.format(java.util.ResourceBundle.getBundle("ru/danilakondr/netalbum/client/gui/Strings").getString("menu.Help.About"), new Object[] {})); // NOI18N
        helpMenu.add(miAbout);

        jMenuBar1.add(helpMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private File selectFolder() {
        JFileChooser dirChooser = new JFileChooser();
        dirChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        
        int result = dirChooser.showOpenDialog(this);
        File directory;
        if (result == JFileChooser.APPROVE_OPTION) {
            directory = dirChooser.getSelectedFile();
            return directory;
        } else {
            return null;
        }
    }
    
    private void error(Object message, String title) {
        SwingUtilities.invokeLater(() -> JOptionPane.showMessageDialog(this, message, title, JOptionPane.ERROR_MESSAGE));
    }
    
    private void initSession(File directory) {
        String serverAddress = cfg.getServerAddress();
        URI serverUri = URI.create(serverAddress);
        
        Session session = new Session();
        addCommonListeners(session, serverAddress, directory.getAbsolutePath());
        session.addOnResponseListener(Response.Type.SESSION_CREATED, (s) -> {
            s.loadImages(directory);
        }, true);
        session.init(serverUri, directory.getName());
    }
    
    private void miPreferencesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPreferencesActionPerformed
        ConfigDialog dlg = new ConfigDialog(this, true, cfg);
        dlg.setVisible(true);
    }//GEN-LAST:event_miPreferencesActionPerformed

    private void miInitSessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miInitSessionActionPerformed
        File directory = selectFolder();
        if (directory == null)
            return;
        
        initSession(directory);
    }//GEN-LAST:event_miInitSessionActionPerformed

    private void miCloseAllSessionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCloseAllSessionsActionPerformed
        int x = JOptionPane.showConfirmDialog(this, 
                "Вы действительно хотите закрыть все сессии?", 
                "Внимание",
                YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        
        if (x == JOptionPane.NO_OPTION)
            return;
        
        for (int i = 0; i < sessionTable.getRowCount(); i++) {
            Session s = sessionTable.getSessionAt(i);
            s.close();
        }
    }//GEN-LAST:event_miCloseAllSessionsActionPerformed

    private void miCloseSessionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCloseSessionsActionPerformed
        if (tblSessionList.getSelectedRowCount() < 1)
            return;

        int[] rows = tblSessionList.getSelectedRows();
        for (int row: rows) {
            Session s = sessionTable.getSessionAt(row);
            s.close();
        }
    }//GEN-LAST:event_miCloseSessionsActionPerformed

    private void miExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miExitActionPerformed
        dispose();
    }//GEN-LAST:event_miExitActionPerformed

    private void viewSession(int index) {
        Session s = sessionTable.getSessionAt(index);
        ViewFolderForm viewer = new ViewFolderForm(s);
        viewer.setVisible(true);
    }
    
    private void miViewSessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miViewSessionActionPerformed
        int selectedRow = tblSessionList.getSelectedRow();
        if (selectedRow == -1)
            return;
        
        viewSession(selectedRow);
    }//GEN-LAST:event_miViewSessionActionPerformed

    private void tblSessionListMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSessionListMousePressed
        Point point = evt.getPoint();
        int clickedRow = tblSessionList.rowAtPoint(point);
        int selectedRow = tblSessionList.getSelectedRow();
        
        if (evt.getClickCount() != 2)
            return;
        
        if (clickedRow == -1)
            return;
        
        if (selectedRow == -1)
            return;
        
        if (clickedRow != selectedRow)
            return;
        
        viewSession(selectedRow);
    }//GEN-LAST:event_tblSessionListMousePressed
    
    private void addCommonListeners(Session session, String serverAddress, String absolutePath) { 
        session.addOnSessionEstablishedListener(s -> sessionTable.addSession(s));
        session.addOnResponseListener(Response.Type.SESSION_CREATED, s -> {
            cfg.addInitiatedSession(
                serverAddress, 
                s.getSessionId(), 
                absolutePath);
        });
        session.addOnSessionClosedListener(s -> sessionTable.removeSession(s));
        session.addOnResponseListener(Response.Type.SESSION_CLOSED, s -> cfg.removeInitiatedSession(s.getUrl(), s.getSessionId()), false);
        
        session.addOnResponseListener(Response.Type.SYNCHRONIZING, (s, r) -> {
            Response.Synchronizing resp = (Response.Synchronizing)r;
            synchronizeSession(s, resp.getChanges());
        });
        session.addOnResponseListener(Response.Type.ERROR, (s, r) -> {
            Response.Error err = (Response.Error)r;
            
            switch (err.getStatus()) {
                case INVALID_REQUEST: {
                    String message = (String)err.getProperty("message");
                    error("Invalid request: " + message, "Error");
                    break;
                }
                case NON_EXISTENT_SESSION: {
                    String sessionId = (String)err.getProperty("sessionId");
                    error("Invalid request: " + sessionId, "Error");
                    break;
                }
                case CLIENT_NOT_CONNECTED: {
                    error("Client not connected", "Error");
                    break;
                } 
                case CLIENT_ALREADY_CONNECTED: {
                    error("Client already connected", "Error");
                    break;
                }
                case NOT_AN_INITIATOR: {
                    error("Not an initiator", "Error");
                    break;
                }
                case NOT_A_VIEWER: {
                    error("Not a viewer", "Error");
                    break;
                }
                case FILE_NOT_FOUND: {
                    String fileName = (String)err.getProperty("fileName");
                    error("File not found: " + fileName, "Error");
                    break;
                }
                case FILE_ALREADY_EXISTS: {
                    String fileName = (String)err.getProperty("fileName");
                    error("File already exists: " + fileName, "Error");
                    break;
                }
                case EXCEPTION: {
                    String message = (String)err.getProperty("message");
                    error("An exception occured on server: " + message, "Error");
                    break;
                }
            }
        });
    }
    
    public void restoreSessions() {
        List<SessionInfo> sessions = cfg.getInitiatedSessions();
        for (SessionInfo sessionInfo : sessions) {
            Session session = new Session();
            addCommonListeners(session, sessionInfo.getUrl(), sessionInfo.getPath());
            session.setPath(sessionInfo.getPath());
            session.restore(URI.create(sessionInfo.getUrl()), sessionInfo.getSessionId());
        }
    }

    private void synchronizeSession(Session session, List<Change> changes) {
        if (session.getSessionType() != Session.Type.INIT_SESSION)
            return;
        
        try {
            Path dirPath = Path.of(session.getPath());
             
            for (Change change: changes) {
                switch (change.getType()) {
                    case RENAME_FILE:
                    case RENAME_DIR:
                        Change.Rename renFile = (Change.Rename)change;
                        Path oldFile = dirPath.resolve(renFile.getOldName());
                        Path newFile = dirPath.resolve(renFile.getNewName());
                        Files.move(oldFile, newFile);
                        break;
                    case ADD_FOLDER:
                        Change.AddFolder mkdir = (Change.AddFolder)change;
                        Path folderName = dirPath.resolve(mkdir.getFolderName());
                        Files.createDirectories(folderName);
                        break;
                }
            }
        }
        catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Failed to synchronize files: " + e);
            e.printStackTrace(System.err);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPopupMenu contextMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem miAbout;
    private javax.swing.JMenuItem miCloseAllSessions;
    private javax.swing.JMenuItem miCloseSessions;
    private javax.swing.JMenuItem miExit;
    private javax.swing.JMenuItem miInitSession;
    private javax.swing.JMenuItem miOpenSession;
    private javax.swing.JMenuItem miPreferences;
    private javax.swing.JMenuItem miViewSession;
    private javax.swing.JTable tblSessionList;
    // End of variables declaration//GEN-END:variables
}
