package ru.danilakondr.netalbum.api.response;

public enum Status {
	  SUCCESS
	, INVALID_REQUEST
	, INVALID_METHOD
	, INVALID_ARGUMENT
	, FILE_NOT_FOUND
	, FILE_ALREADY_EXISTS
	, NON_EXISTENT_SESSION
	, ERROR
	, EXCEPTION
	, SESSION_EXITS
	, SYNCHRONIZING
	;
}
